- hosts: ipsec
  roles:
    - role: ipsec-strongswan
      vars:
        CURRENT_ROLES: [ipsec-server,ca]
        CA_FQDN: ca.mysite.com
        IPSEC_FQDN: vpn.mysite.com
        IPSEC_IP: 192.168.50.10


- hosts: clients
  roles:
    - role: ipsec-strongswan
      vars:
        CURRENT_ROLES: [ipsec-client]    
        CA_FQDN: ca.mysite.com
        IPSEC_FQDN: vpn.mysite.com
        IPSEC_IP: 192.168.50.10            

