- name: Check if epel repository is installed
  yum:
    name: epel-release
    state: latest
- name: Install necessary packages (for IKE strongswan is used)
  yum:
    name: [strongswan]
    state: latest
- name: Generate Private RSA key for CA
  shell: /sbin/strongswan pki --gen --type rsa --size 4096 --outform pem > {{IPSEC_PRIV_KEY_PATH}}/{{CA_KEY_NAME}}
- name: Generate Self-Signed Certificate for CA
  shell: /sbin/strongswan pki --self --ca --lifetime 3650 --in {{IPSEC_PRIV_KEY_PATH}}/{{CA_KEY_NAME}} --type rsa --dn "{{CA_DN}}" --flag serverAuth  --flag clientAuth --flag crlSign  --flag ocspSigning  --outform pem > {{IPSEC_CERT_PATH}}/{{CA_CERT_NAME}}
