- name: restart strongswan
  become: yes
  service:
    name: strongswan-swanctl
    state: restarted
- name: enable strongswan
  become: yes
  service:
    name: strongswan-swanctl
    enabled: yes
- name: reload strongswan
  become: yes
  service:
    name: strongswan-swanctl
    state: reloaded 