- name: Apply conf for Side-to-Side VPN
  template:
    src: "../templates/left-side.conf.j2"
    dest: "{{ IPSEC_CONF_PATH }}/left-side.conf"
- name: Apply conf for end-VPN users
  template:
    src: "../templates/roadwarrior.conf.j2"
    dest: "{{ IPSEC_CONF_PATH }}/roadwarrior.conf"    
- name: Run swanctl to apply configuration
  service:
    name: strongswan-swanctl
    state: restarted
    enabled: yes
#- name: Establish IPSec connection
#  shell: /usr/sbin/swanctl --initiate --child net-net